/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uneatlantico.forms;

import com.sun.javafx.scene.control.skin.VirtualFlow;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.util.*;
import java.util.logging.Level;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import com.uneatlantico.database.*;
import com.uneatlantico.data.Filtro;
import java.sql.SQLException;
import javax.sound.midi.SysexMessage;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import org.apache.commons.lang.StringUtils;
import org.apache.tika.exception.TikaException;

import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

/**
 *
 * @author manuel.coto
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private Conexion conn = new Conexion();
    private List<List> datosPalabras = new ArrayList<>();
    private  Logger Log = Logger.getLogger(this.getClass());
    public Main() throws IOException, TikaException, SQLException {
        initComponents();
        PropertyConfigurator.configure("src\\main\\resources\\files\\log4j.properties");
        JLabel fondo = new JLabel();
        fondo.setSize(this.PaneImage.getWidth(), this.PaneImage.getHeight());
        try {
            BufferedImage image = ImageIO.read(new File("src/main/resources/files/logo.png"));
            fondo.setIcon(new ImageIcon(image));
            this.PaneImage.add(fondo);
        } catch (IOException ex) {
           Log.error(ex.getMessage());
        }
        setTree();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        PanelBusqueda = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        PaneImage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        itemIndexarCarpeta = new javax.swing.JMenuItem();
        itemIndexarArchivo = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTree1);

        PanelBusqueda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        PaneImage.setBackground(new java.awt.Color(255, 153, 102));
        PaneImage.setForeground(new java.awt.Color(255, 153, 51));
        PaneImage.setPreferredSize(new java.awt.Dimension(305, 105));

        javax.swing.GroupLayout PaneImageLayout = new javax.swing.GroupLayout(PaneImage);
        PaneImage.setLayout(PaneImageLayout);
        PaneImageLayout.setHorizontalGroup(
            PaneImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );
        PaneImageLayout.setVerticalGroup(
            PaneImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelBusquedaLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PaneImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBusquedaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PaneImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        menuArchivo.setText("Archivo");

        itemIndexarCarpeta.setText("Indexar Carpeta");
        itemIndexarCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIndexarCarpetaActionPerformed(evt);
            }
        });
        menuArchivo.add(itemIndexarCarpeta);

        itemIndexarArchivo.setText("Indexar Archivo");
        itemIndexarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIndexarArchivoActionPerformed(evt);
            }
        });
        menuArchivo.add(itemIndexarArchivo);

        jMenuBar1.add(menuArchivo);

        menuOpciones.setText("Opciones");

        jMenuItem1.setText("Borrar todo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuOpciones.add(jMenuItem1);

        jMenuItem2.setText("Borrar Carpeta");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuOpciones.add(jMenuItem2);

        jMenuBar1.add(menuOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(PanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemIndexarCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIndexarCarpetaActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory( new File("."));
        chooser.setDialogTitle("Elige el directorio");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if(chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
        {
                    Log.info("Se selecciono "+chooser.getSelectedFile().getName());

            File fiel = chooser.getSelectedFile();
            /*String[] directories = fiel.list(new FilenameFilter() {
  @Override
  public boolean accept(File current, String name) {
    return new File(current, name).canRead();
  }
});
            Log.info(Arrays.toString(directories));*/
          
        List<String> padres = new ArrayList();
        if(!conn.CarpetExist(fiel.getName())){
        padres.add(0, fiel.getName());
        conn.InsertCarpeta(fiel.getName(), 1, "");
        listFilesForFolder(fiel,0,padres);
        }
            try {
                Index();
            } catch (IOException ex) {
                Log.error(ex.getMessage());
            } catch (SQLException ex) {
                Log.error(ex.getMessage());
            } catch (TikaException ex) {
                Log.error(ex.getMessage());
            }
        }
    }//GEN-LAST:event_itemIndexarCarpetaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       conn.borrarTodo();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemIndexarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIndexarArchivoActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new File("."));
        chooser.setDialogTitle("Elige el archivo");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Archivo de texto","txt"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Office doc","doc"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("Office excel","xlsx"));
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("PDF","pdf"));
        if(chooser.showOpenDialog(this)==JFileChooser.APPROVE_OPTION)
        {
            if(conn.CarpetExist(chooser.getCurrentDirectory().getName()))
            {
                if(conn.InsertArchivo(chooser.getSelectedFile().getName(), chooser.getSelectedFile().getPath(), chooser.getCurrentDirectory().getName()))
                    Log.info("> "+chooser.getName());
            }
            else{
                if(conn.InsertCarpeta(chooser.getCurrentDirectory().getName(), 1, ""))
                    if(conn.InsertArchivo(chooser.getSelectedFile().getName(), chooser.getSelectedFile().getPath(), chooser.getCurrentDirectory().getName()))
                    Log.info("> "+chooser.getName());
            }
        }
        try {
            Index();
        } catch (IOException ex) {
            Log.error(ex.getMessage());
        } catch (TikaException ex) {
           Log.error(ex.getMessage());
        } catch (SQLException ex) {
            Log.error(ex.getMessage());
        }
    }//GEN-LAST:event_itemIndexarArchivoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if(txtBusqueda.getText().isEmpty()){
            MensajeAlerta("Escribe algo que buscar");
        }
        else{
            buscarPalabra(txtBusqueda.getText());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
        if(evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)
        {
            if(txtBusqueda.getText().isEmpty()){
                MensajeAlerta("Escribe algo que buscar");
            }
            else
            buscarPalabra(txtBusqueda.getText());
        }
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Borrarfrm borrar = new Borrarfrm("la carpeta",conn,this);
        borrar.setVisible(true);
        this.setVisible(false);
        Thread ttt = new Thread(()->{while(!this.isVisible()){if(borrar.resultado){
        Log.debug("Esta reindexando despues de borrar");
            try {
                Index();
            } catch (IOException ex) {
                Log.error(ex.getMessage());
            } catch (TikaException ex) {
                Log.error(ex.getMessage());
            } catch (SQLException ex) {
                Log.error(ex.getMessage());
            }Log.debug("Termino de Indexar");break;}
        }});
        ttt.start();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed
/**
 * Funcionessssssssssssssssssssssssssss
 * @param folder
 * @param index
 * @param padres 
 */
    public void listFilesForFolder(final File folder, int index,List<String>padres) {
        int indexx=index;
        Log.info(index);
    for (final File fileEntry : folder.listFiles(new Filtro())) {
        if (fileEntry.isDirectory()) {
                padres.add( fileEntry.getName());
                if(conn.InsertCarpeta(fileEntry.getName(), 0, padres.get(index)))
                    Log.info((StringUtils.repeat("    ",indexx+1))+"-"+fileEntry.getName());
                indexx++;
            listFilesForFolder(fileEntry,indexx,padres);
        } else {
            Log.info(padres.get(indexx));
            if(conn.InsertArchivo(fileEntry.getName(), fileEntry.getPath(), padres.get(index)))
             Log.info(StringUtils.repeat("   ",indexx+2)+">"+fileEntry.getName());
        }
    }
}
    public void MensajeAlerta(String mensaje){
        JOptionPane.showMessageDialog(null, mensaje,"Alerta",JOptionPane.WARNING_MESSAGE);
    }
    
    public void buscarPalabra(String palabra){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Documento");
        model.addColumn("Tf-IDF");
        model=conn.GetDataPalabra(model, palabra);
        jTable1.setModel(model);
    }
    
    public void Index() throws IOException, TikaException, SQLException{
        List<List> todo = conn.Indexacion(this.datosPalabras);
        if(!todo.get(0).isEmpty()){
        datosPalabras=todo.get(0);
                   conn.CalculoPalabra(datosPalabras,todo.get(todo.size()-1));
                   datosPalabras=new ArrayList();
                   setTree();}
        else
            setTree();
        
        
    }
    
    public void setTree(){
      List<String>Roots = new ArrayList();
      Roots = conn.getRaices(Roots);
      DefaultMutableTreeNode root = new DefaultMutableTreeNode();
      Roots.forEach(item->{
          DefaultMutableTreeNode Carpeta = new DefaultMutableTreeNode(item);
          if(conn.HasChilds(item))
          {   
             Carpeta = conn.getChilds(Carpeta, item);
          }
          if(conn.HasFiles(item))
          {
              Carpeta = conn.getFiles(Carpeta, item);
          }
          root.add(Carpeta);
          });
        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree1.setModel(model);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Logger Logg = Logger.getLogger(Main.class);
                try { 
                    new Main().setVisible(true);
                } catch (IOException ex) {
                    Logg.error(ex.getMessage());
                } catch (TikaException ex) {
                    Logg.error(ex.getMessage());
                } catch (SQLException ex) {
                    Logg.error(ex.getMessage());
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneImage;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JMenuItem itemIndexarArchivo;
    private javax.swing.JMenuItem itemIndexarCarpeta;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JTextField txtBusqueda;
    // End of variables declaration//GEN-END:variables

  
}
